@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package team.covertdragon.springfestival.module.fortune;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;