@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package team.covertdragon.springfestival.fortune;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;